// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0pm1eAu-yclrQ3lIzt97WXmzcAaK_WE',
    appId: '1:172721746926:web:3ec3efdbabace39c0a94ff',
    messagingSenderId: '172721746926',
    projectId: 'smart-tv-98713',
    authDomain: 'smart-tv-98713.firebaseapp.com',
    storageBucket: 'smart-tv-98713.appspot.com',
    measurementId: 'G-QPPKLR749H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0H71JU-IKDlqtA326Q4bQm242C5V8tw',
    appId: '1:172721746926:android:588f291cb60d8be00a94ff',
    messagingSenderId: '172721746926',
    projectId: 'smart-tv-98713',
    storageBucket: 'smart-tv-98713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkEK5U_SBUr6i-cXoVmOKtXyBil6Ye5Hw',
    appId: '1:172721746926:ios:47343f69553ebd0b0a94ff',
    messagingSenderId: '172721746926',
    projectId: 'smart-tv-98713',
    storageBucket: 'smart-tv-98713.appspot.com',
    iosClientId: '172721746926-fakr11ebavq8fdvphqbr1m59r9one53p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkEK5U_SBUr6i-cXoVmOKtXyBil6Ye5Hw',
    appId: '1:172721746926:ios:47343f69553ebd0b0a94ff',
    messagingSenderId: '172721746926',
    projectId: 'smart-tv-98713',
    storageBucket: 'smart-tv-98713.appspot.com',
    iosClientId: '172721746926-fakr11ebavq8fdvphqbr1m59r9one53p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTv',
  );
}
